// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_m3FXVvxEKGWHtCsYoK6eUT8ZsmCJ9tc',
    appId: '1:420579105285:web:f311d90d6f7ad6d24c9a6c',
    messagingSenderId: '420579105285',
    projectId: 'gadidosti-68f19',
    authDomain: 'gadidosti-68f19.firebaseapp.com',
    storageBucket: 'gadidosti-68f19.firebasestorage.app',
    measurementId: 'G-D91BYP6H9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyYepaMwZLax5eJGeygMVhT76bJUsnpRY',
    appId: '1:420579105285:android:1d35eae383d64d0e4c9a6c',
    messagingSenderId: '420579105285',
    projectId: 'gadidosti-68f19',
    storageBucket: 'gadidosti-68f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkoF1wOA49S9DNsDSKfSPmm45JnAwxrNU',
    appId: '1:420579105285:ios:6601a9f5fa2d74d94c9a6c',
    messagingSenderId: '420579105285',
    projectId: 'gadidosti-68f19',
    storageBucket: 'gadidosti-68f19.firebasestorage.app',
    iosBundleId: 'com.example.ssk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkoF1wOA49S9DNsDSKfSPmm45JnAwxrNU',
    appId: '1:420579105285:ios:6601a9f5fa2d74d94c9a6c',
    messagingSenderId: '420579105285',
    projectId: 'gadidosti-68f19',
    storageBucket: 'gadidosti-68f19.firebasestorage.app',
    iosBundleId: 'com.example.ssk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_m3FXVvxEKGWHtCsYoK6eUT8ZsmCJ9tc',
    appId: '1:420579105285:web:ce792cf9757c5e1f4c9a6c',
    messagingSenderId: '420579105285',
    projectId: 'gadidosti-68f19',
    authDomain: 'gadidosti-68f19.firebaseapp.com',
    storageBucket: 'gadidosti-68f19.firebasestorage.app',
    measurementId: 'G-BHJJ8M1YJ1',
  );
}
